### ISSUE TITLE
Issue with data containing an ' 

### ISSUE THREAD

**Issue by jeffreynelson** [lucasalexander/AlexanderDevelopment.ConfigDataMover#11]
When we export the data from CRM with a ' the data in the json file contains ???

**Comment by lucasalexander** [comment]
I'm unable to replicate this error in my local environment. Can you successfully export the data from CRM using advanced find? What versions of CRM and the data mover are you using?

**Comment by jeffreynelson** [comment]
We are using CRM 2016 with SP1 and data mover V2.1.  I just downloaded the latest version of data mover and will give that a try and try the advanced find as well.

**Comment by jeffreynelson** [comment]
We found the issue.  We have a process that runs to uncompress the JSON file.  That changed the encoding.

We changed the encoding to UTF8 and it is now correct.

Thanks

On Aug 15, 2018, at 8:35 AM, Lucas Alexander <notifications@github.com<mailto:notifications@github.com>> wrote:

EXTERNAL EMAIL



I'm unable to replicate this error in my local environment. Can you successfully export the data from CRM using advanced find? What versions of CRM and the data mover are you using?

**Comment by lucasalexander** [comment]
Great, thanks for confirming.
