### ISSUE TITLE
Special characters in exported data "'" are converted to "?" in the json export file.

### ISSUE THREAD

**Issue by jeffreynelson** [lucasalexander/AlexanderDevelopment.ConfigDataMover#14]
The following section was copied from the json file right after the export was completed.  NOTE: The file has not been updated by any other process. 

"AttributeValue":"HB-Update Member?s Marital Status to Divorced","AttributeType"

The file encoded of the json file is UTF8.  We are using DataMover version 2.1.6285.28822

**Comment by jeffreynelson** [comment]
I have updated to the latest release v2.4.6587.18905 and the issue is the same.

**Comment by lucasalexander** [comment]
What is the character that's getting turned into the "?" character? I ran a quick test in one of my dev orgs with this string as an attribute value: ``test><][}{?/~`"'test``
It gets serialized in the export like so: ``{"AttributeName":"new_name","AttributeValue":"test><][}{?/~`\"'test","AttributeType":"System.String"}``
