### ISSUE TITLE
Error running job

### ISSUE THREAD

**Issue by diver7** [lucasalexander/AlexanderDevelopment.ConfigDataMover#6]
Does this tool work with CRM 2016 Online? I'm getting this error on a simple Account 1 step job.

![image](https://cloud.githubusercontent.com/assets/18582794/15160474/5c49775c-16bf-11e6-9134-3051b8e8242a.png)

**Comment by lucasalexander** [comment]
This has been fixed in the latest release v1.10.1.1.
