### ISSUE TITLE
; in connection password

### ISSUE THREAD

**Issue by raphaelmoser** [lucasalexander/AlexanderDevelopment.ConfigDataMover#7]
Hi

When I try to use the tool with an AD account that has a semicolon in its password, I get a "Validation failed: Format of the the initialization string does not conform to the specification". Is there a way to escape that somehow in the connection string?

Greetings

**Comment by lucasalexander** [comment]
Hi Ralph,

Try wrapping the password in quotes like so: 
Url=http://crm.contoso.com/xrmContoso; Domain=CONTOSO; Username=jsmith; Password='password_with_;';

**Comment by raphaelmoser** [comment]
Hey Lucas

Thanks for your answer! Yes, when I change that in the job xml file, the job runs without problems.
`"url=https://server.domain.com;username=user;domain=domain.loc;password='pw_with;semicolons';"`

Greetings
