### ISSUE TITLE
HELP! I can't copy Access Team Template

### ISSUE THREAD

**Issue by fvakiliev** [lucasalexander/AlexanderDevelopment.ConfigDataMover#9]
Hi Alexander!

I can not copy _Team Templates_ from my DEV environment to TEST and PROD. Yours documentation and instructions very short and have't provided detailed information about this job. Also I can't load sample config _**teamtemplates-noconnection.xml**_ (loaded 2 years ago).

My invironment:
1. D365 On-premises v8.2.2.112 (bosh DEV and TEST)
2. Your ConfigDataMover v2.3.6541.17849 - Success connect to Source and Target

Regards,
OldCat

PS: Please help. Very needed!

**Comment by lucasalexander** [comment]
Please provide the job file (with connection details removed), the ConfigDataMover.log file and the RecordError .log file.

**Comment by fvakiliev** [comment]
Hi Alexander!

One step: Create and Update one entity record _teamtemplate_.
Log files attached.

PS: With Account all works fine.
[ConfigDataMover.log](https://github.com/lucasalexander/AlexanderDevelopment.ConfigDataMover/files/1534322/ConfigDataMover.log)
[RecordError.log](https://github.com/lucasalexander/AlexanderDevelopment.ConfigDataMover/files/1534323/RecordError.log)

**Comment by fvakiliev** [comment]
Also config attached.
[Create One Team Template.txt](https://github.com/lucasalexander/AlexanderDevelopment.ConfigDataMover/files/1534333/Create.One.Team.Template.txt)

**Comment by lucasalexander** [comment]
I believe I have fixed the issue. Please try the latest release and let me know if that solves your problem. https://github.com/lucasalexander/AlexanderDevelopment.ConfigDataMover/releases/tag/v2.3.6550.16299.

**Comment by fvakiliev** [comment]
The same errors. Do not work!

**Comment by lucasalexander** [comment]
I was able to reproduce the original error in my environment, and then this update solved the problem for me. Please attach your updated log files so I can review again.

**Comment by fvakiliev** [comment]
ok. Are you in onlin? Can I contact you?

**Comment by fvakiliev** [comment]
Logs
[ConfigDataMover.log](https://github.com/lucasalexander/AlexanderDevelopment.ConfigDataMover/files/1540061/ConfigDataMover.log)
[RecordError.log](https://github.com/lucasalexander/AlexanderDevelopment.ConfigDataMover/files/1540062/RecordError.log)
[One Team Template Config.xml.txt](https://github.com/lucasalexander/AlexanderDevelopment.ConfigDataMover/files/1540067/One.Team.Template.Config.xml.txt)

**Comment by lucasalexander** [comment]
You are apparently missing the teamtemplateid and objecttypecode attributes from your FetchXML.

**Comment by fvakiliev** [comment]
Tryшп it...

**Comment by fvakiliev** [comment]
NO! The same error accrued: MESSAGE: An unexpected error occurred.
Logs the same too. I try only Create, Update - no difference.
We must continue the battle ...

**Comment by lucasalexander** [comment]
Please attach your updated job and log files so I can review again.

**Comment by fvakiliev** [comment]
Logs;

[New config 23-20.txt](https://github.com/lucasalexander/AlexanderDevelopment.ConfigDataMover/files/1540198/New.config.23-20.txt)
[ConfigDataMover.log](https://github.com/lucasalexander/AlexanderDevelopment.ConfigDataMover/files/1540201/ConfigDataMover.log)
[RecordError.log](https://github.com/lucasalexander/AlexanderDevelopment.ConfigDataMover/files/1540202/RecordError.log)

**Comment by lucasalexander** [comment]
You are still missing the objecttypecode attribute that I mentioned in my earlier response.

**Comment by fvakiliev** [comment]
I think that everything revolves around the objecttypecode.
You need to understand that the objecttypecode can be different in the source/target object. And this is normal!

**Comment by lucasalexander** [comment]
My tool will only work for transferring the access team templates if the objecttypecode is provided and is the same in each environment.

**Comment by fvakiliev** [comment]
I tried enter the _objecttypecode_ in the fetchXML - the same result.

**Comment by fvakiliev** [comment]
But this is impossible! When a solution is transferred to a new environment (org), the custom entities receive new objecttypecode. It is truth!

**Comment by fvakiliev** [comment]
How work **_GUID mapping_** feature?

**Comment by fvakiliev** [comment]
And yes! I try to copy **_Team Templates_** for a custom entity.
I think that we need to retrieve the **_objecttypecode_** from the target org. (from target connection).

**Comment by fvakiliev** [comment]
Dear Alexander! You are here?

**Comment by lucasalexander** [comment]
If the objecttypecode is different in your source and target, I don't think I can help you without writing a lot of new code. The functionality is actually working as I designed it, so I'm going to close this issue now. If you would like to submit a patch to add the source/destination remapping, I would be happy to review it.
